from . import domain_detail
from . import hosting_detail
from . import other_service
from . import project_income
from . import project_expense
from . import project_project
from . import expiry_config
from . import res_config_settings
from . import account_payment
from . import account_move
from . import account_payment_register
