{
    'name': 'Extended Project Management',
    'version': '1.0',
    'depends': ['project', 'hr', 'contacts', 'mail', 'bus', 'base_setup', 'account', 'sale_project'],
    'author': 'Your Name',
    'category': 'Project',
    'description': 'Manage domains, hosting, income, and expenses for each project with expiry notifications',
    'data': [
        'security/ir.model.access.csv',
        'data/domain_expiry_email_template.xml',
        'data/remind_client_actions.xml',
        'data/automated_email_cron.xml',
        'data/domain_expiry_cron.xml',
        'data/expiry_notification_cron.xml',
        'data/test_email_actions.xml',
        'data/debug_email_action.xml',
        'data/payment_sync_cron.xml',
        'views/domain_detail_views.xml',
        'views/hosting_detail_views.xml',
        'views/other_service_views.xml',
        'views/project_income_views.xml',
        'views/project_expense_views.xml',
        'views/project_project_views.xml',
        'views/project_menus.xml',
        'data/payment_sync_actions.xml',
        'views/expiry_config_views.xml',
        'views/automated_email_settings.xml',
        'views/account_payment_views.xml',
        'views/password_toggle_assets.xml',
    ],
    'demo': [
        'data/demo_data.xml',
    ],

    'installable': True,
    'application': True,
}
